apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xzones.example.upbound.io
spec:
  group: example.upbound.io
  names:
    kind: XZone
    plural: xzones
  claimNames:
    kind: Zone
    plural: zones
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Zones define management zones within the cloud native platform
        type: object
        properties:
          spec:
            description: Specification of the desired state of the Composite Resource
            type: object
            properties:
              parameters:
                description: Configuration parameters for XZones
                type: object
                properties:
                  id:
                    type: string
                    description: Zone ID used for identification throughout the platform
          status:
            description: Most recently observed state of the Composite Resource
            type: object
            properties:
              zoneController:
                description: Robot ID that interacts with the zone
                type: string