apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-servicehub
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/opusdavei/configuration-servicehub
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-azuread
      # renovate: datasource=github-releases depName=upbound/provider-azuread
      version: "v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-kubernetes
      version: "v0.11.4"
    - provider: xpkg.upbound.io/upbound/provider-upbound
      # renovate: datasource=github-releases depName=upbound/provider-upbound
      version: "v0.7.0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      # renovate: datasource=github-releases depName=upbound/function-patch-and-transform
      version: "v0.2.1"
